# Generated by Django 4.0.5 on 2022-06-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_login_history', '0002_auto_20200607_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='external_ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='lat',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='lon',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
